# Header
nav:
  Home: /index
  Posts: /archives
  resume: "/about/"
  # Categories: /category
  # Tags: /tag
  # Publications: /publications  # This renders `source/publications.md`
  # "About Me": /about  # This renders `source/about.md`

email: isaachyw@umich.edu

# favicon
favicon: /img/isaac_logo.png

# logo
logo: /img/isaac_logo.png

# links
links:
  Github: https://github.com/isaachyw
  # ZhiHu: https://www.zhihu.com/people/chen-ying-fa-34
  # Twitter:
  # Weibo:

# analytics
google_analytics:
baidu_analytics:

# mathjax
fancybox: true

# mathjax
mathjax: true

# echarts
echarts: true

# busuanzi
busuanzi: true

# mermaid
mermaid:
  enable: true
  # Available themes: default | dark | forest | neutral
  theme: default

# giscus
giscus:
  enable:
  repo:
  repo_id:
  category:
  category_id:
  mapping:
