# ---------------------------------------------------------------
# Site Information Settings
# ---------------------------------------------------------------

# Head info
head:
  favicon: "/img/isaac_logo.png"
  keywords: yuewen hou isaac umich
  backgroundpic: "img/park.jpg"

Intro:
  name: Yuewen(Isaac) Hou
  slogan: "<q>In a moment, passes sorrow <br> That which passes will be dear</q>"
  HeadButton: Isaac

Nav:
  Home_name: Home
  is_use_categories: true
  categories_name: categories
  is_use_archives: true
  archives_name: archive

  #Social
  # for more icons, please see http://fontawesome.io/icons/#brand
  icon:
    github: https://github.com/isaachyw
    linkedin: https://www.linkedin.com/in/yuewen-hou-127177254

  pages:
    resume:
      link: "/about/"
    # group:
    #   link: "/group/"
    gallery:
      link: "/gallery/"
    tags:
      link: "/tag/"
    contact:
      link: "/contact/"

MainFirst:
  name: Yuewen Hou
  description: Hi, I am an undergraduate an University of Michigan and<br>Shanghai JiaoTong University major in CS and ECE. <br/>My research interest orbit around Computer architecture and system.
  pic_url: /images/i.jpg
  goto_ulr: ""

Gallery:
  title: world thought
  description: Collection of photography

# ---------------------------------------------------------------
# Style Settings
# ---------------------------------------------------------------

# Custom code Render System 自定义代码渲染
# default dark funky okaidia twilight coy solarized  可选项
# link to review : http://prismjs.com/index.html   官网预览
prism: coy

# Custom Fonts
fonts: FZLTCXHJW, "Helvetica Neue", Helvetica, "PingFang SC", "Hiragino Sans GB", "Microsoft YaHei", "FZLTCXHJW", Arial, sans-serif

# Comment Systems
# Available value of "use":
#     duoshuo | disqus | disqus_click | changyan
comment:
  use: disqus_click
  shortname: http-miccall-tech
  duoshuo_thread_key_type: path
  duoshuo_embed_js_url: "https://static.duoshuo.com/embed.js"
  changyan_appid:
  changyan_conf:
  changyan_thread_key_type: path
  # 使用 valine 请先执行 npm install valine --save
  valine: # Valine Comment System https://github.com/xCss/Valine
    on: true
    appId: "your appId"
    appKey: "your appkey"
    notify: true
    verify: false
    placeholder: Please leave your footprints
    avatar: ""
    avatar_cdn: https://gravatar.loli.net/avatar/ # avatar CDN address, default gravatar.loli.net
    pageSize: 10 # comments of one page

# Search Systems
# Available value:
#     swiftype | google | local
search:
  use: google
  swiftype_key: Just another fine responsive

# Leancloud Views
leancloud:
  enable: false
  app_id: #你的 app_id
  app_key: #你的 app_key
  av_core_mini: "https://cdn1.lncld.net/static/js/av-core-mini-0.6.1.js"

# Busuanzi 不蒜子 Views
busuanzi:
  enable: true
  all_site_uv: true
  post_pv: true
  busuanzi_pure_mini_js: "https://dn-lbstatics.qbox.me/busuanzi/2.3/busuanzi.pure.mini.js"

# Mathjax 支持库
mathjax:
  enable: true
  per_page: false
  cdn: //cdn.bootcss.com/mathjax/2.7.1/latest.js?config=TeX-AMS-MML_HTMLorMML
